// myunits-vue/src/components/ResultBox.vue
<script setup>
defineProps({
  result: Number,
  error: String,
});
</script>

<template>
  <section class="result-box" :class="{ error: error }">
    <h2 v-if="error">{{ error }}</h2>
    <h2 v-else-if="result !== null">Resultado: {{ result }}</h2>
    <h2 v-else>Resultado pendiente</h2>
  </section>
</template>

// myunits-svelte/src/lib/components/ResultBox.svelte
<script>
  import { fade } from "svelte/transition";
  import { converter } from "../stores/converter.js";
</script>

<section class:error={$converter.error} class="result-box">
  {#if $converter.error}
    <h2>{$converter.error}</h2>
  {:else if $converter.result !== null}
    <h2 transition:fade>Resultado: {$converter.result}</h2>
  {:else}
    <h2>Resultado pendiente</h2>
  {/if}
</section>
