// myunits-svelte/src/lib/components/UnitForm.svelte
<script>
  import CategorySelector from "./CategorySelector.svelte";
  import { getCategory } from "../data/units.js";
  import { converter } from "../stores/converter.js";

  $: units = getCategory($converter.category)?.units ?? [];
</script>

<form class="unit-form" on:submit|preventDefault={converter.convert}>
  <CategorySelector />

  <label class="field">
    <span>Valor</span>
    <input type="number" step="any" bind:value={$converter.value} />
  </label>

  <div class="unit-row">
    <label class="field">
      <span>Desde</span>
      <select bind:value={$converter.from}>
        {#each units as unit}
          <option value={unit.id}>{unit.label}</option>
        {/each}
      </select>
    </label>

    <button class="swap-button" type="button" on:click={converter.swapUnits}>
      Cambiar
    </button>

    <label class="field">
      <span>Hacia</span>
      <select bind:value={$converter.to}>
        {#each units as unit}
          <option value={unit.id}>{unit.label}</option>
        {/each}
      </select>
    </label>
  </div>

  <button type="submit">Convertir</button>
</form>

// myunits-vue/src/components/UnitForm.vue
<script setup>
defineProps({
  categories: Array,
  category: String,
  units: Array,
  value: [Number, String],
  from: String,
  to: String,
});

const emit = defineEmits([
  "update:category",
  "update:value",
  "update:from",
  "update:to",
  "swap",
  "convert",
]);
</script>

<template>
  <form class="unit-form" @submit.prevent="emit('convert')">
    <label class="field">
      <span>Categoría</span>
      <select
        :value="category"
        @change="emit('update:category', $event.target.value)"
      >
        <option
          v-for="conversionCategory in categories"
          :key="conversionCategory.id"
          :value="conversionCategory.id"
        >
          {{ conversionCategory.label }}
        </option>
      </select>
    </label>

    <label class="field">
      <span>Valor</span>
      <input
        type="number"
        step="any"
        :value="value"
        @input="emit('update:value', $event.target.value)"
      />
    </label>

    <div class="unit-row">
      <label class="field">
        <span>Desde</span>
        <select :value="from" @change="emit('update:from', $event.target.value)">
          <option v-for="unit in units" :key="unit.id" :value="unit.id">
            {{ unit.label }}
          </option>
        </select>
      </label>

      <button class="swap-button" type="button" @click="emit('swap')">
        Cambiar
      </button>

      <label class="field">
        <span>Hacia</span>
        <select :value="to" @change="emit('update:to', $event.target.value)">
          <option v-for="unit in units" :key="unit.id" :value="unit.id">
            {{ unit.label }}
          </option>
        </select>
      </label>
    </div>

    <button type="submit">Convertir</button>
  </form>
</template>
